# Generated by Django 5.2.10 on 2026-01-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='synopsis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='annee',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
