# Generated by Django 5.2.10 on 2026-01-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_film_poster_url_film_synopsis_alter_film_annee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='ordre',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
