# Generated by Django 5.2.10 on 2026-01-10 20:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_film_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date_visionnage',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
