# Generated by Django 5.2.10 on 2026-01-11 01:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_film_utilisateur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='films_partages', to=settings.AUTH_USER_MODEL),
        ),
    ]
