# Generated by Django 5.2.10 on 2026-01-11 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_film_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='participants',
        ),
    ]
