# Generated by Django 5.2.10 on 2026-01-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_film_participants_alter_film_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='date_visionnage',
            field=models.DateField(default='2025-01-01'),
        ),
    ]
